name: 'Download Cedar Schema'
description: 'Download the Cedar Schema for a Common Fate deployment.'
author: 'Common Fate'

branding:
  icon: download
  color: gray-dark

inputs:
  oidc-issuer:
    description:
      'The OIDC issuer to use for authenticating to your Common Fate deployment'
    required: true
  oidc-client-id:
    description:
      'The OIDC client ID to use for authenticating to your Common Fate
      deployment'
    required: true
  oidc-client-secret:
    description:
      'The OIDC client secret to use for authenticating to your Common Fate
      deployment'
    required: true
  deployment-url:
    description: 'Your Common Fate deployment URL.'
    required: true
  save-schema-file-to:
    description: 'The output file location to save the schema to.'
    required: true
    default: './commonfate.cedarschema.json'

runs:
  using: node20
  main: dist/index.js
